"""update quality_rating constraint

Revision ID: 90eb279fd688
Revises: 08eb9e1eac6d
Create Date: 2025-11-10 17:22:38.609841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90eb279fd688"
down_revision: Union[str, Sequence[str], None] = "08eb9e1eac6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_translations_composite"))
        batch_op.drop_index(batch_op.f("idx_translations_composite_created"))
        batch_op.drop_index(batch_op.f("idx_translations_composite_file"))
        batch_op.drop_index(batch_op.f("idx_translations_created_at"))
        batch_op.drop_index(batch_op.f("idx_translations_file_category"))
        batch_op.drop_index(batch_op.f("idx_translations_language_created_at"))
        batch_op.drop_index(batch_op.f("idx_translations_poem_language"))
        batch_op.drop_index(batch_op.f("idx_translations_poem_type"))
        batch_op.drop_index(batch_op.f("idx_translations_poet_subdir"))
        batch_op.drop_index(batch_op.f("idx_translations_quality_rating"))
        batch_op.drop_index(batch_op.f("idx_translations_type_language"))
        batch_op.drop_index(batch_op.f("ix_translations_id"))
        batch_op.drop_index(batch_op.f("ix_translations_poem_id"))
        batch_op.drop_index(batch_op.f("ix_translations_target_language"))
        batch_op.drop_index(batch_op.f("ix_translations_translator_type"))

    op.drop_table("translations")
    with op.batch_alter_table("workflow_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_created_at"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_mode_status"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_poem_id"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_poem_mode"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_poem_status"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_status"))
        batch_op.drop_index(batch_op.f("idx_workflow_tasks_status_created_at"))
        batch_op.drop_index(batch_op.f("ix_workflow_tasks_id"))

    op.drop_table("workflow_tasks")
    with op.batch_alter_table("human_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_human_notes_created_at"))
        batch_op.drop_index(batch_op.f("idx_human_notes_translation_created_at"))
        batch_op.drop_index(batch_op.f("ix_human_notes_id"))
        batch_op.drop_index(batch_op.f("ix_human_notes_translation_id"))

    op.drop_table("human_notes")
    with op.batch_alter_table("translation_workflow_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_workflow_steps_ai_log_id"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_cost"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_duration"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_step_metrics"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_tokens"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_translation_id"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_type_order"))
        batch_op.drop_index(batch_op.f("idx_workflow_steps_workflow_id"))
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_ai_log_id"))
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_cost"))
        batch_op.drop_index(
            batch_op.f("ix_translation_workflow_steps_duration_seconds")
        )
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_step_type"))
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_tokens_used"))
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_translation_id"))
        batch_op.drop_index(batch_op.f("ix_translation_workflow_steps_workflow_id"))

    op.drop_table("translation_workflow_steps")
    with op.batch_alter_table("ai_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_ai_logs_created_at"))
        batch_op.drop_index(batch_op.f("idx_ai_logs_mode_created_at"))
        batch_op.drop_index(batch_op.f("idx_ai_logs_model_created_at"))
        batch_op.drop_index(batch_op.f("idx_ai_logs_translation_model"))
        batch_op.drop_index(batch_op.f("ix_ai_logs_id"))
        batch_op.drop_index(batch_op.f("ix_ai_logs_model_name"))
        batch_op.drop_index(batch_op.f("ix_ai_logs_translation_id"))
        batch_op.drop_index(batch_op.f("ix_ai_logs_workflow_mode"))

    op.drop_table("ai_logs")
    with op.batch_alter_table("poems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_poems_created_at"))
        batch_op.drop_index(batch_op.f("idx_poems_language_created_at"))
        batch_op.drop_index(batch_op.f("idx_poems_poet_name_created_at"))
        batch_op.drop_index(batch_op.f("idx_poems_poet_title"))
        batch_op.drop_index(batch_op.f("ix_poems_id"))
        batch_op.drop_index(batch_op.f("ix_poems_poem_title"))
        batch_op.drop_index(batch_op.f("ix_poems_poet_name"))
        batch_op.drop_index(batch_op.f("ix_poems_source_language"))

    op.drop_table("poems")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poems",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("poet_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("poem_title", sa.VARCHAR(length=300), nullable=False),
        sa.Column("source_language", sa.VARCHAR(length=10), nullable=False),
        sa.Column("original_text", sa.TEXT(), nullable=False),
        sa.Column("metadata_json", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("poems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_poems_source_language"),
            ["source_language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_poems_poet_name"), ["poet_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_poems_poem_title"), ["poem_title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_poems_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_poems_poet_title"),
            ["poet_name", "poem_title"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_poems_poet_name_created_at"),
            ["poet_name", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_poems_language_created_at"),
            ["source_language", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_poems_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "ai_logs",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("translation_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("model_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("workflow_mode", sa.VARCHAR(length=20), nullable=False),
        sa.Column("token_usage_json", sa.TEXT(), nullable=True),
        sa.Column("cost_info_json", sa.TEXT(), nullable=True),
        sa.Column("runtime_seconds", sa.FLOAT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["translation_id"], ["translations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_logs_workflow_mode"),
            ["workflow_mode"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ai_logs_translation_id"),
            ["translation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ai_logs_model_name"), ["model_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ai_logs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_ai_logs_translation_model"),
            ["translation_id", "model_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_ai_logs_model_created_at"),
            ["model_name", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_ai_logs_mode_created_at"),
            ["workflow_mode", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_ai_logs_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "translation_workflow_steps",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("translation_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("ai_log_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("workflow_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("step_type", sa.VARCHAR(length=30), nullable=False),
        sa.Column("step_order", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("model_info", sa.TEXT(), nullable=True),
        sa.Column("tokens_used", sa.INTEGER(), nullable=True),
        sa.Column("prompt_tokens", sa.INTEGER(), nullable=True),
        sa.Column("completion_tokens", sa.INTEGER(), nullable=True),
        sa.Column("duration_seconds", sa.FLOAT(), nullable=True),
        sa.Column("cost", sa.FLOAT(), nullable=True),
        sa.Column("additional_metrics", sa.TEXT(), nullable=True),
        sa.Column("translated_title", sa.VARCHAR(length=500), nullable=True),
        sa.Column("translated_poet_name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["ai_log_id"], ["ai_logs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["translation_id"], ["translations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("translation_workflow_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_workflow_id"),
            ["workflow_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_translation_id"),
            ["translation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_tokens_used"),
            ["tokens_used"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_step_type"),
            ["step_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_duration_seconds"),
            ["duration_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_cost"),
            ["cost"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translation_workflow_steps_ai_log_id"),
            ["ai_log_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_workflow_id"),
            ["workflow_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_type_order"),
            ["translation_id", "step_order"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_translation_id"),
            ["translation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_tokens"),
            ["tokens_used"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_step_metrics"),
            ["step_type", "cost", "duration_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_duration"),
            ["duration_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_cost"), ["cost"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_steps_ai_log_id"),
            ["ai_log_id"],
            unique=False,
        )

    op.create_table(
        "human_notes",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("translation_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("note_text", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["translation_id"], ["translations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("human_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_notes_translation_id"),
            ["translation_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_human_notes_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_human_notes_translation_created_at"),
            ["translation_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_human_notes_created_at"),
            ["created_at"],
            unique=False,
        )

    op.create_table(
        "workflow_tasks",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("poem_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("source_lang", sa.VARCHAR(length=10), nullable=False),
        sa.Column("target_lang", sa.VARCHAR(length=10), nullable=False),
        sa.Column("workflow_mode", sa.VARCHAR(length=20), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("progress_percentage", sa.INTEGER(), nullable=False),
        sa.Column("result_json", sa.TEXT(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["poem_id"], ["poems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflow_tasks_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_status_created_at"),
            ["status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_poem_status"),
            ["poem_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_poem_mode"),
            ["poem_id", "workflow_mode"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_poem_id"), ["poem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_mode_status"),
            ["workflow_mode", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_workflow_tasks_created_at"),
            ["created_at"],
            unique=False,
        )

    op.create_table(
        "translations",
        sa.Column("id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("poem_id", sa.VARCHAR(length=26), nullable=False),
        sa.Column("translator_type", sa.VARCHAR(length=10), nullable=False),
        sa.Column("translator_info", sa.VARCHAR(length=200), nullable=True),
        sa.Column("target_language", sa.VARCHAR(length=10), nullable=False),
        sa.Column("translated_text", sa.TEXT(), nullable=False),
        sa.Column("quality_rating", sa.INTEGER(), nullable=True),
        sa.Column("raw_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("poet_subdirectory", sa.VARCHAR(length=100), nullable=True),
        sa.Column("relative_json_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("file_category", sa.VARCHAR(length=12), nullable=True),
        sa.Column("translated_poem_title", sa.TEXT(), nullable=True),
        sa.Column("translated_poet_name", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(["poem_id"], ["poems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("translations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_translations_translator_type"),
            ["translator_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translations_target_language"),
            ["target_language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_translations_poem_id"), ["poem_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_translations_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_translations_type_language"),
            ["translator_type", "target_language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_quality_rating"),
            ["quality_rating"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_poet_subdir"),
            ["poet_subdirectory"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_poem_type"),
            ["poem_id", "translator_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_poem_language"),
            ["poem_id", "target_language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_language_created_at"),
            ["target_language", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_file_category"),
            ["file_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_composite_file"),
            ["poet_subdirectory", "file_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_composite_created"),
            ["poem_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_translations_composite"),
            ["poem_id", "target_language", "translator_type"],
            unique=False,
        )

    # ### end Alembic commands ###
