"""Add poet-based file organization fields to Translation model

Revision ID: add_poet_file_organization_fields
Revises: 94bcac9585c9
Create Date: 2025-10-24 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_poet_file_organization_fields"
down_revision: Union[str, Sequence[str], None] = "94bcac9585c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the file_category enum type
    file_category_enum = sa.Enum(
        "recent", "poet_archive", name="file_category_enum"
    )
    file_category_enum.create(op.get_bind())

    # Add new columns to translations table
    op.add_column(
        "translations",
        sa.Column("poet_subdirectory", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "translations",
        sa.Column("relative_json_path", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "translations",
        sa.Column("file_category", file_category_enum, nullable=True),
    )

    # Add indexes for the new fields
    op.create_index(
        "idx_translations_poet_subdir",
        "translations",
        ["poet_subdirectory"],
        unique=False,
    )
    op.create_index(
        "idx_translations_file_category",
        "translations",
        ["file_category"],
        unique=False,
    )
    op.create_index(
        "idx_translations_composite_file",
        "translations",
        ["poet_subdirectory", "file_category"],
        unique=False,
    )

    # Add additional performance indexes
    op.create_index(
        "idx_translations_quality_rating",
        "translations",
        ["quality_rating"],
        unique=False,
    )
    op.create_index(
        "idx_translations_composite",
        "translations",
        ["poem_id", "target_language", "translator_type"],
        unique=False,
    )
    op.create_index(
        "idx_translations_composite_created",
        "translations",
        ["poem_id", "created_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index(
        "idx_translations_composite_created", table_name="translations"
    )
    op.drop_index("idx_translations_composite", table_name="translations")
    op.drop_index("idx_translations_quality_rating", table_name="translations")
    op.drop_index("idx_translations_composite_file", table_name="translations")
    op.drop_index("idx_translations_file_category", table_name="translations")
    op.drop_index("idx_translations_poet_subdir", table_name="translations")

    # Drop columns
    op.drop_column("translations", "file_category")
    op.drop_column("translations", "relative_json_path")
    op.drop_column("translations", "poet_subdirectory")

    # Drop enum type
    sa.Enum(name="file_category_enum").drop(op.get_bind())

    # ### end Alembic commands ###
