# VPSWeb Repository System Configuration
# Version: 0.3 - Localhost-only deployment

repository:
  # SQLite database configuration (WAL mode for performance)
  database_url: "sqlite+aiosqlite:///./repository_root/repo.db"
  repo_root: "./repository_root"
  auto_create_dirs: true
  enable_wal_mode: true  # Write-Ahead Logging for better concurrency

# Security configuration (localhost-only, v0.3)
security:
  # No authentication required for localhost deployment
  # Authentication (Argon2 + BasicAuth) moved to v0.4+
  require_auth: false
  session_timeout: 3600  # 1 hour (for future v0.4+)
  api_key_required: false

# Server configuration (localhost-only)
server:
  host: "127.0.0.1"
  port: 8000
  reload: false
  debug: false
  workers: 1  # Single worker for SQLite

# Data configuration
data:
  default_language: "en"
  supported_languages: ["en", "zh-Hans", "zh-Hant"]
  default_license: "CC-BY-4.0"
  max_poem_length: 10000
  max_translation_length: 20000
  enable_validation: true

# Background task configuration
background_tasks:
  enabled: true
  max_concurrent_jobs: 3
  job_timeout: 300  # 5 minutes
  cleanup_interval: 3600  # 1 hour

  # Enhanced task management
  max_retry_attempts: 3
  retry_delay: 60  # Base retry delay in seconds
  max_queue_size: 100
  queue_check_interval: 1.0  # Queue processing interval in seconds
  task_retention_hours: 24

  # Task-specific timeouts
  task_timeouts:
    translation: 600  # 10 minutes
    maintenance: 300  # 5 minutes
    cleanup: 120  # 2 minutes
    backup: 1800  # 30 minutes

  # Resource limits
  max_memory_mb: 512
  max_cpu_percent: 80.0

  # Queue management
  enable_priority_queue: true
  pause_on_overload: true
  overload_threshold: 0.9

# Logging configuration
logging:
  level: "INFO"
  format: "json"  # Structured JSON logging
  file_path: "./repository_root/logs/repository.log"
  max_file_size: "10MB"
  backup_count: 5

# Integration configuration
integration:
  vpsweb:
    # Use existing vpsweb configuration
    config_path: "config"
    workflow_mode: "hybrid"  # Default workflow mode
    timeout: 300  # 5 minutes for translation jobs

# Web UI configuration
web_ui:
  title: "VPSWeb Repository"
  description: "Central repository for poetry translations"
  theme: "default"  # Basic theme, advanced themes in v0.4+
  items_per_page: 20
  enable_search: true
  enable_comparison: true

# Performance configuration
performance:
  database_pool_size: 1  # SQLite doesn't need pooling
  query_timeout: 30
  enable_query_cache: true
  cache_size: 1000

  # Performance monitoring
  enable_metrics: true
  metrics_retention_days: 7

  # Memory management
  gc_threshold: 1000
  max_memory_usage: 1024  # MB

# Task monitoring configuration
task_monitoring:
  enable_health_checks: true
  health_check_interval: 60  # seconds
  enable_task_metrics: true
  metrics_history_size: 1000

  # Alert thresholds
  failed_task_threshold: 5
  queue_size_warning: 50
  memory_usage_warning: 0.8

  # Task lifecycle monitoring
  track_task_lifecycle: true
  enable_task_tracing: false

# System resource configuration
system_resources:
  enable_resource_monitoring: true
  resource_check_interval: 30  # seconds

  # CPU thresholds
  max_cpu_usage: 80.0  # percentage
  cpu_warning_threshold: 70.0

  # Memory thresholds
  max_memory_usage_percent: 85.0
  memory_warning_threshold: 75.0

  # Disk thresholds
  max_disk_usage_percent: 90.0
  disk_warning_threshold: 80.0