# WeChat Official Account Configuration
# This file contains configuration for WeChat article publishing functionality

# WeChat API Credentials (REQUIRED)
# Get these from your WeChat Official Account backend: https://mp.weixin.qq.com/
appid: "${WECHAT_APPID}"
secret: "${WECHAT_SECRET}"

# API Configuration
base_url: "https://api.weixin.qq.com"

# Token Management
token_cache_path: "outputs/.cache/wechat_token.json"

# Request Timeouts (seconds)
timeouts:
  connect: 5.0
  read: 20.0

# Retry Configuration
retry:
  attempts: 3
  backoff: "exponential"
  base_delay: 0.5

# Article Generation Settings
article_generation:
  include_translation_notes: true
  copyright_text: "【著作权声明】\n本译文与译注完全由知韵(VoxPoetica)AI工具生成制作，仅供学习交流使用。原作品版权归原作者所有，如有侵权请联系删除。翻译内容未经授权，不得转载、不得用于商业用途。若需引用，请注明出处。"
  #article_template: "default"  # References config/html_templates/wechat_articles/default.html
  article_template: "codebuddy"  # References config/html_templates/wechat_articles/codebuddy.html

  # Cover image configuration
  default_cover_image_path: "config/html_templates/cover_image_big.jpg"  # Default cover image path (relative to project root)
  default_local_cover_image_name: "cover_image_big.jpg"  # Default local cover image filename in wechat_articles/slug directory

  # LLM configuration for translation notes synthesis
  # Note: LLM model configuration is now in config/models.yaml under wechat_translation_notes
  model_type: "non_reasoning"  # Model type: reasoning or non_reasoning

# Publishing Settings
publishing:
  # Save to draft folder by default (safer for manual review)
  save_as_draft: true
  # Enable comments on published articles
  enable_comments: true
  # Allow only fans to comment
  fans_only_comments: false
  # Auto-publish from draft (disable for manual control)
  auto_publish: false

# Output Settings
output:
  # Default output directory for WeChat articles
  default_directory: "outputs/wechat_articles"

  # File naming patterns
  filename_patterns:
    html: "article.html"
    metadata: "metadata.json"
    publish_result: "publish_result.json"

# Content Settings
content:
  # Default author name
  default_author: "知韵VoxPoetica"

  # Title format
  title_format: "【知韵译诗】{poem_title}（{poet_name}）"

  # Digest settings
  digest:
    min_length: 100
    max_length: 120
    auto_generate: true

# WeChat API Error Codes
api_error_codes:
  invalid_access_token: 40001
  rate_limit_exceeded: 45009
  invalid_media_id: 40007

# Development Settings
development:
  # Enable debug logging
  debug: false

  # Dry run mode (no actual API calls)
  dry_run: false

  # Verbose output
  verbose: false

  # Mock API responses for testing
  mock_api: false